name: py311-fastlane-bot
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11  # You can specify the Python version you want

  # Conda packages
  - psutil~=5.9.6
  - requests~=2.31.0
  - python-dateutil~=2.8.2
  - typing-extensions~=4.7.1
  - python-dotenv~=0.16.0
  - joblib~=1.2.0
  - pandas~=1.5.2
  - pyarrow~=11.0.0
  - networkx~=3.0
  - cvxpy~=1.3.1
  - matplotlib~=3.7.1
  - hexbytes~=0.3.1
  - click~=8.1.3
  - setuptools~=67.6.1
  - protobuf~=4.24.4
  - tqdm~=4.64.1
  - web3~=6.11.2
  - nest-asyncio~=1.5.8
  - black~=23.11.0
  - pytest~=7.4.0
  - pytest-mock~=3.12.0
  - monkeytype~=23.3.0

  # PyPI packages (ignore installed versions)
  - pip:
      - dataclass_wizard~=0.22.2
      - packaging==21.3
      - alchemy-sdk~=0.1.1
