# This workflow will run black and flake8 on every push and pull request
# For more information see: https://github.com/psf/black


name: Black Formatting

on: # Set your workflow to run on push events to the develop and all feature branches
  push:
      
  # Set your workflow to run on pull request events that target the main branch
  pull_request:
    branches: 
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black
      - name: Install Black Jupyter
        run: pip install jupyter-black
      - name: Run black --check fastlane_bot/
        run: black --check fastlane_bot/ --exclude fastlane_bot/data/
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black fastlane_bot/ --exclude fastlane_bot/data/
          git config --global user.name 'mikewcasale'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push
