# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Bump version, create release, publish, and generate changelog

on:
  push:
    branches:
      - release-*

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --force-reinstall
      - name: Install bumpversion
        run: pip install bumpversion
      - name: Bump version
        run: bumpversion minor --current-version $(python -c "from fastlane_bot import __version__; print(__version__)") fastlane_bot/__init__.py
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
  release:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PACKAGE_VERSION: $(python -c "from fastlane_bot import __version__; print(__version__)")
        with:
          tag_name: v$PACKAGE_VERSION
          release_name: v$PACKAGE_VERSION
          draft: true
          prerelease: true
  generate_changelog:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
  publish:
    needs: generate_changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python setup.py install
      - name: Build package
        run: python setup.py sdist
      - name: Build wheel
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_API_TOKEN }}

